name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
        
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
        
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
        
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    
    - name: Print ENV
      run: env
      
    - name: Display JSON payload contents
      run: cat $GITHUB_EVENT_PATH
    
    - name: 'Find & Replace'
      uses: warrenbuckley/Token-Replace-Action@releases/v1
      with:
        find: '{{MyPlaceholder}}'
        replace: 'HELLO WORLD'
